export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_SINGLE_REPO_SUCCESS  = 'LOAD_SINGLE_REPO_SUCCESS';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
export const LOAD_FAV_CATS_SUCCESS = 'LOAD_FAV_CATS_SUCCESS';